### ISSUE TITLE
Timer may block other futures from being processed

### ISSUE THREAD

**Issue by application-developer-DA** [tokio-rs/tokio-timer#9] opened 2017-03-01 10:05 UTC
Hi,

I'm not sure if it is a bug or some expected behavior, but I've noticed that spawning tokio timer may prevent other futures from being processed. I've noticed that issue when I worked on my work project, it uses tokio timer. My application has an architecture which is quite similar to the [chat.rs](https://github.com/tokio-rs/tokio-core/blob/master/examples/chat.rs) example from tokio-core. So basically I have a client which connects to the server. After the connection to the server is done, I split the stream to `Sink` and `Stream` futures and then I have a `for_each` futures for messages coming in where I process them, and `tx.forward(sink)`. So basically the client processes incoming messages and uses `tx.send()` whenever some messages has to be sent, then `tx` is forwarded to the `Sink` part. Like in `chat.rs` both futures are combined with `select()`. Then I've realized that my application has to have a timer which checks the state of the system each 100ms and performs some actions which may involve sending a message to the `Sink` via `tx`. So I decided to use a tokio-timer for that. I created a timer and tried to use `select()` to combine the timer future to those 2 other futures, unfortunately I could not succeed in that, the compiler gave me huge compile time errors which I don't know how to solve. So what I decided to do is to use `Handle::spawn()` method to spawn a timer future. When I did that, I've noticed that after the timer is started, other futures (futures which handle sending and receiving messages) are never being processed, i.e. after the timer future is `spawn`ed, no messages are sent or received on the client side. I was able to workaround this issue by increasing the timer timeout time to 200ms (maybe it did not work because the tick time was equal to the timeout time?), but it turned out soon that it is not a good solution as **sometimes** the situation repeats, I have a feeling that it happens when the code which is executed after the timer timeout takes longer than 200ms.

I used slightly modified chat example from tokio-core to reproduce the problems I've had. This is what happens in case if I set the interval to 100ms, in this case the client never receives or sends any messages, seems like the timer prevents other futures from being processed by the tokio:

```rust
//! A simple example of hooking up stdin/stdout to a TCP stream.
//!
//! This example will connect to a server specified in the argument list and
//! then forward all data read on stdin to the server, printing out all data
//! received on stdout.
//!
//! Note that this is not currently optimized for performance, especially around
//! buffer management. Rather it's intended to show an example of working with a
//! client.

extern crate futures;
extern crate tokio_core;
extern crate tokio_timer;

use std::env;
use std::io::{self, Read, Write};
use std::net::SocketAddr;
use std::thread;
use std::time::Duration;

use futures::{Sink, Future, Stream};
use futures::sync::mpsc;
use tokio_core::reactor::Core;
use tokio_core::io::{Io, EasyBuf, Codec};
use tokio_core::net::TcpStream;
use tokio_timer::Timer;

fn main() {
    // Parse what address we're going to connect to
    let addr = env::args().nth(1).unwrap_or_else(|| {
        panic!("this program requires at least one argument")
    });
    let addr = addr.parse::<SocketAddr>().unwrap();

    // Create the event loop and initiate the connection to the remote server
    let mut core = Core::new().unwrap();
    let handle = core.handle();
    let tcp = TcpStream::connect(&addr, &handle);

    // Right now Tokio doesn't support a handle to stdin running on the event
    // loop, so we farm out that work to a separate thread. This thread will
    // read data from stdin and then send it to the event loop over a standard
    // futures channel.
    let (stdin_tx, stdin_rx) = mpsc::channel(0);
    thread::spawn(|| read_stdin(stdin_tx));
    let stdin_rx = stdin_rx.map_err(|_| panic!()); // errors not possible on rx

    // After the TCP connection has been established, we set up our client to
    // start forwarding data.
    //
    // First we use the `Io::framed` method with a simple implementation of a
    // `Codec` (listed below) that just ships bytes around. We then split that
    // in two to work with the stream and sink separately.
    //
    // Half of the work we're going to do is to take all data we receive on
    // stdin (`stdin_rx`) and send that along the TCP stream (`sink`). The
    // second half is to take all the data we receive (`stream`) and then write
    // that to stdout. Currently we just write to stdout in a synchronous
    // fashion.
    //
    // Finally we set the client to terminate once either half of this work
    // finishes. If we don't have any more data to read or we won't receive any
    // more work from the remote then we can exit.
    let mut stdout = io::stdout();
    let client = tcp.and_then(|stream| {
        let (sink, stream) = stream.framed(Bytes).split();
        let send_stdin = stdin_rx.forward(sink);
        let write_stdout = stream.for_each(move |buf| {
            stdout.write_all(buf.as_slice())
        });

        let timer = Timer::default(); // currently the tick duration is 100ms
        let timer = timer.interval(Duration::from_millis(100)).for_each(move |_| {
            println!("timeout");
            Ok(())
        });
        handle.spawn(timer.map_err(|_| ()));

        send_stdin.map(|_| ())
                  .select(write_stdout.map(|_| ()))
                  .then(|_| Ok(()))
    });

    // And now that we've got our client, we execute it in the event loop!
    core.run(client).unwrap();
}

/// A simple `Codec` implementation that just ships bytes around.
///
/// This type is used for "framing" a TCP stream of bytes but it's really just a
/// convenient method for us to work with streams/sinks for now. This'll just
/// take any data read and interpret it as a "frame" and conversely just shove
/// data into the output location without looking at it.
struct Bytes;

impl Codec for Bytes {
    type In = EasyBuf;
    type Out = Vec<u8>;

    fn decode(&mut self, buf: &mut EasyBuf) -> io::Result<Option<EasyBuf>> {
        if buf.len() > 0 {
            let len = buf.len();
            Ok(Some(buf.drain_to(len)))
        } else {
            Ok(None)
        }
    }

    fn encode(&mut self, data: Vec<u8>, buf: &mut Vec<u8>) -> io::Result<()> {
        buf.extend(data);
        Ok(())
    }
}

// Our helper method which will read data from stdin and send it along the
// sender provided.
fn read_stdin(mut rx: mpsc::Sender<Vec<u8>>) {
    let mut stdin = io::stdin();
    loop {
        let mut buf = vec![0; 1024];
        let n = match stdin.read(&mut buf) {
            Err(_) |
            Ok(0) => break,
            Ok(n) => n,
        };
        buf.truncate(n);
        rx = rx.send(buf).wait().unwrap();
    }
}
```

If I change the interval time to 200ms, it seems that the problem is solved (like I did when I worked in my project), but as said before, sometimes it still may keep other futures from being processed, I guess that it may happen if the code which is executed after the timer timeout is fired takes longer than the interval between timer. And indeed, if I change 

```rust
        let timer = timer.interval(Duration::from_millis(100)).for_each(move |_| {
            println!("timeout");
            Ok(())
        });
```

to

```rust
            use std::{thread, time};
            println!("timeout");
            thread::sleep(time::Duration::from_millis(205));
            println!("timeout2");
            Ok(())
```

then the problem occurs again.

Can you please suggest me what to do in such cases and if it is a bug? I want to start a timer with the interval of N milliseconds and I want to ensure that other futures are also executed.

**Comment by alexcrichton** [comment] 2017-03-01 17:36
Note that spawning doesn't spawn a thread, just a future. If you call `thread::sleep` it'll block the reactor, which may be causing problems here?

In general futures are unable to block the current thread as it'll bring the whole system to a grinding halt.

**Comment by application-developer-DA** [comment] 2017-03-01 19:08
>> Note that spawning doesn't spawn a thread, just a future.

Yeah, I know. But I did not expect that a spawned task can somehow prevent other task from being processed.

>> you call thread::sleep it'll block the reactor, which may be causing problems here?

I thought about that, but the real code which I have inside my real project, does not have any sleeps. I have a timer there, the interval is set to 200ms and when the timer fires, I do some proessing. I've noticed that in some cases  (I believe it happens when the timer "handler" processing timer exceeds 200ms (interval time)) other futures are not executed, i.e. reading and writing futures (which work in within a different task) did not do any process.

>> In general futures are unable to block the current thread as it'll bring the whole system to a grinding halt.

The timer future, which was spawned in a separate task (I used `Handler::spawn`) did not block the thread, I was receiving timeout "events" every time they happened, but in some cases, only the timer task was "active", another tasks (reading and writnig futures) did not make any progress at all (they resumed their activity immediately after I changed the conditions [I reduced the time for processing stuff in `for_each` timer future]).

**Comment by alexcrichton** [comment] 2017-03-01 19:48
> But I did not expect that a spawned task can somehow prevent other task from being processed.

Yeah this should be correct, modulo starvation (e.g. if one task just spins in a loop preventing others from running)

Do you have the example code you were working with? It may be more helpful to just take a peek at that. If it's a bug in the library then that's invaluable for reproduction and confirming a fix, and if it's a local bug then it'd also be invaluable to help diagnose!

**Comment by application-developer-DA** [comment] 2017-03-02 12:23
You can use the code from the modified version of chat which I've shown above, my code has very similar architecture.

Have a look at:
```rust
    let mut stdout = io::stdout();
    let client = tcp.and_then(|stream| {
        let (sink, stream) = stream.framed(Bytes).split();
        let send_stdin = stdin_rx.forward(sink);
        let write_stdout = stream.for_each(move |buf| {
            stdout.write_all(buf.as_slice())
        });

        let timer = Timer::default(); // currently the tick duration is 100ms
        let timer = timer.interval(Duration::from_millis(100)).for_each(move |_| {
            println!("timeout");
            Ok(())
        });
        handle.spawn(timer.map_err(|_| ()));

        send_stdin.map(|_| ())
                  .select(write_stdout.map(|_| ()))
                  .then(|_| Ok(()))
    });
```

Let's call the code that resides inside the `for_each` as a `timer event handler`. I've just made a test. I decided to measure the time for the `timer event handler` in my project, so basically that's what I did:

```rust
        let timer = timer.interval(Duration::from_millis(200)).for_each(move |_| {
            let start = PreciseTime::now(); 
            // here is some code which executes some business logic of the application
            my_object.do_some_processing();
            debug!("Time spent: {}", start.to(PreciseTime::now()).num_milliseconds());
            Ok(())
        });
```

I've noticed that the "freeze" (when all other futures except timer future are not processed) occurs when the `Time spent` becomes greater than 200ms (which is an interval duration in my case). Normally the `Time spent` is between 20-150 milliseconds, but in some cases in my application it may grow up to 350ms, when it happens `Timer spent` becomes ~320ms and all other futures (except the timer future) never receive a processing time. The system returns to its normal state when the processing time decreases to the normal value.

Seems like the timer's task in such cases somehow remains active all the time and consumes all the time. It does not allow tokio to switch to another task (which does the networking patr in my case).

Is there a way to say something like: "Please, check the `event queue` (or something similar) and try to process other tasks before getting back to the current task?". At the moment it seems that the timer task is just always active (when the timer handler time exceeds the interval time) and so it does not let the tokio to work on other tasks.

**Comment by alexcrichton** [comment] 2017-03-02 17:27
I think I'm still confused. In the first code snippet of your last comment the timer doesn't actually do anything? It just prints out information but otherwise isn't hooked up into message processing.

In the second example, the `do_some_processing` function takes hundreds of milliseconds? Is that doing CPU bound work or is it blocking? If it's blocking that's the problem (it shouldn't block) but if it's doing CPU bound work that's different.

**Comment by application-developer-DA** [comment] 2017-03-03 09:15
Ah, ok, I'll try to explain.

In my application I have some processing code inside and I always had this issue, in order to test the behavior of the timer and create an issue I decided to write some SSCCE.

In the first example I wrote the timer which indeed does not do anything. And even with such code it is enough to reproduce the bug. You can see that the interval time in the first code snippet is 100ms; 100ms is also a default value for the tick duration, based on this information I assumed that the bug occurrs due to the the interval time which is equal to the default tick duration.

To workaround the issue, I decided to increase the interval time to 200ms (so the tick duration remains 100ms as before), when I tried that, it solved the issue, (at least I thought that the issue was solved) so I changed the interval to 200ms in my application as well. But then it turned out that the problem is reproducible even when the interval is bigger than the tick duration.

So if you use the first code snippet, where the timer did nothing and the interval is equal to 100ms, it will produce a behavior which I described.

If you take my 2nd snippet, where the timer does something and the interval is 200ms, it will work as long as the event handler execution takes less than the interval time (200ms).


> In the second example, the do_some_processing function takes hundreds of milliseconds? Is that doing CPU bound work or is it blocking? If it's blocking that's the problem (it shouldn't block) but if it's doing CPU bound work that's different.

Sometimes the function (not always, the behavior depends on some internal state of the application and business logic) does some trivial stuff which takes less than 30ms, in other cases it does more CPU extensive tasks such as JPEG/PNG encoding which may take 150-320 milliseconds.

**Comment by alexcrichton** [comment] 2017-03-03 15:38
Sounds quite suspicious! @carllerche mind taking a look (you're more familiar with the impl than I)

**Comment by carllerche** [comment] 2017-03-03 17:35
It's looking like this behavior isn't a bug per se, but it's a sharp edge with coarse timers.

The implementation of Interval can definitely be fixed to handle this specific case, but there are subtle things at play besides that.

The quick fix is, assuming that you are only setting timeouts in the 100ms range, you should reduce the interval size to ~10ms or so. I would say that the interval size should be no bigger than 1/10th the smallest timeout set.

**Comment by application-developer-DA** [comment] 2017-03-06 10:47
> The quick fix is, assuming that you are only setting timeouts in the 100ms range, you should reduce the interval size to ~10ms or so.

Did you mean the tick duration? If so, then I tried to set the tick duration to 10ms (the timer interval was set to 200ms), but unfortunately it did not help.

**Comment by carllerche** [comment] 2017-03-07 04:53
It would be helpful to have a minimal test case that illustrated the failure then. I did the following and it seemed to work fine:

```rust
extern crate futures;
extern crate tokio_core;
extern crate tokio_timer;

use std::env;
use std::io::{self, Read, Write};
use std::net::SocketAddr;
use std::thread;
use std::time::Duration;

use futures::{Sink, Future, Stream};
use futures::sync::mpsc;
use tokio_core::reactor::Core;
use tokio_core::io::{Io, EasyBuf, Codec};
use tokio_core::net::TcpStream;
use tokio_timer::Timer;

fn main() {
    // Parse what address we're going to connect to
    let addr = env::args().nth(1).unwrap_or_else(|| {
        panic!("this program requires at least one argument")
    });
    let addr = addr.parse::<SocketAddr>().unwrap();

    // Create the event loop and initiate the connection to the remote server
    let mut core = Core::new().unwrap();
    let handle = core.handle();
    let tcp = TcpStream::connect(&addr, &handle);

    // Right now Tokio doesn't support a handle to stdin running on the event
    // loop, so we farm out that work to a separate thread. This thread will
    // read data from stdin and then send it to the event loop over a standard
    // futures channel.
    let (stdin_tx, stdin_rx) = mpsc::channel(0);
    thread::spawn(|| read_stdin(stdin_tx));
    let stdin_rx = stdin_rx.map_err(|_| panic!()); // errors not possible on rx

    // After the TCP connection has been established, we set up our client to
    // start forwarding data.
    //
    // First we use the `Io::framed` method with a simple implementation of a
    // `Codec` (listed below) that just ships bytes around. We then split that
    // in two to work with the stream and sink separately.
    //
    // Half of the work we're going to do is to take all data we receive on
    // stdin (`stdin_rx`) and send that along the TCP stream (`sink`). The
    // second half is to take all the data we receive (`stream`) and then write
    // that to stdout. Currently we just write to stdout in a synchronous
    // fashion.
    //
    // Finally we set the client to terminate once either half of this work
    // finishes. If we don't have any more data to read or we won't receive any
    // more work from the remote then we can exit.
    let mut stdout = io::stdout();
    let client = tcp.and_then(|stream| {
        let (sink, stream) = stream.framed(Bytes).split();
        let send_stdin = stdin_rx.forward(sink);
        let write_stdout = stream.for_each(move |buf| {
            stdout.write_all(buf.as_slice())
        });

        let timer = tokio_timer::wheel()
            .tick_duration(Duration::from_millis(10))
            .build();

        let timer = timer.interval(Duration::from_millis(100)).for_each(move |_| {
            println!("timeout");
            Ok(())
        });
        handle.spawn(timer.map_err(|_| ()));

        send_stdin.map(|_| ())
                  .select(write_stdout.map(|_| ()))
                  .then(|_| Ok(()))
    });

    // And now that we've got our client, we execute it in the event loop!
    core.run(client).unwrap();
}

/// A simple `Codec` implementation that just ships bytes around.
///
/// This type is used for "framing" a TCP stream of bytes but it's really just a
/// convenient method for us to work with streams/sinks for now. This'll just
/// take any data read and interpret it as a "frame" and conversely just shove
/// data into the output location without looking at it.
struct Bytes;

impl Codec for Bytes {
    type In = EasyBuf;
    type Out = Vec<u8>;

    fn decode(&mut self, buf: &mut EasyBuf) -> io::Result<Option<EasyBuf>> {
        if buf.len() > 0 {
            let len = buf.len();
            Ok(Some(buf.drain_to(len)))
        } else {
            Ok(None)
        }
    }

    fn encode(&mut self, data: Vec<u8>, buf: &mut Vec<u8>) -> io::Result<()> {
        buf.extend(data);
        Ok(())
    }
}

// Our helper method which will read data from stdin and send it along the
// sender provided.
fn read_stdin(mut rx: mpsc::Sender<Vec<u8>>) {
    let mut stdin = io::stdin();
    loop {
        let mut buf = vec![0; 1024];
        let n = match stdin.read(&mut buf) {
            Err(_) |
            Ok(0) => break,
            Ok(n) => n,
        };
        buf.truncate(n);
        rx = rx.send(buf).wait().unwrap();
    }
}
```

**Comment by application-developer-DA** [comment] 2017-03-07 09:58
> I did the following and it seemed to work fine:

It does work as long as the timer handler requires less than 100ms to complete. Currently the only thing you do when the timeout is triggered, you print a single line to the console. But what will happen in case if the code inside the timer event handler is more complex, i.e. what would be if in some cases this code takes more than 100ms? That's exactly the case which happens in my actual project - my actual code looks similar to your example, but instead of `println!()` it has some business logic, which may take more than 100ms to finish (**sometimes** it takes 110ms), what would happen in such case?

Let's image the following situation: we started a timer with the interval of 100ms and the tick duration of 20ms, the timer runs well and everything works as expected. The code which is executed whenever the timeout is triggerred is a bit more complex: in most cases it only prints something to the console, but sometimes it does some more complex computations which may take up to 120ms. Let's say that we got to the point when the timer event handler starts doing some complex computations (takes ~120ms to finish).

**The expected behavior:**

Timestamp | The actions taken by the tokio
------------ | -------------
Nms | The timeout event is triggered => we started executing our complex code (which will take 120ms to finish)
N+20ms | Our code is still doing some processing, i.e. tokio does nothing at this point
N+40ms | Our code is still doing some processing, i.e. tokio does nothing at this point
N+60ms | Our code is still doing some processing, i.e. tokio does nothing at this point
N+80ms | Our code is still doing some processing, i.e. tokio does nothing at this point
N+100ms | Our code is still doing some processing, i.e. tokio does nothing at this point
N+120ms | Our code is still doing some processing, i.e. tokio does nothing at this point
(N+121ms) | Our code has finished the execution, so the control is passed back to the tokio
N+140ms | Tokio knows that the next timer timeout should occur at N+200ms, since there is nothing the tokio-timer can do right now, we let other tasks (futures) to work
N+160ms | Tokio knows that the next timer timeout should occur at N+200ms, since there is nothing the tokio-timer can do right now, we let other tasks (futures) to work
N+180ms | Tokio knows that the next timer timeout should occur at N+200ms, since there is nothing the tokio-timer can do right now, we let other tasks (futures) to work
N+200ms | The timeout event is triggered => we started executing our complex code (which will take 120ms to finish)
N+220 ms | Our code is still doing some processing, i.e. tokio does nothing at this point
N+240 ms | Our code is still doing some processing, i.e. tokio does nothing at this point
... | ...

It seems that unfortunately it does not work like this. Currently during the steps (N+140ms), (N+160ms), (N+180ms) other tasks do not make any progress, I don't know what tokio (or tokio-timer) does within these periods of time, for some reason it does not switch to other tasks/futures which leads to the problem I'm trying to describe.

**Comment by carllerche** [comment] 2017-03-07 17:44
Sorry, I don't understand what you mean by "tasks don't make progress".

**Comment by application-developer-DA** [comment] 2017-03-07 18:29
They do not receive any processing time (or pending something). It behaves like if tokio's "execution context" (if I can use this term here) is always on the timer's task and never switches to other tasks (when the conditions described in my previous comments are met).

I'll give you a couple examples, maybe it will make things clearer:
1. If we're talking about them in terms of your example: there is 2 tasks -- the 1st one contains the futures which send and receive data and the 2nd one is spawned for the timer future. So, when the conditions for triggering the bug are met, the 1st future "will not work", i.e. you will not see any messages coming from the server, i.e. you will not get inside:
```rust
        let write_stdout = stream.for_each(move |buf| {
            stdout.write_all(buf.as_slice())
        });
```
block. Also you won't be able to send anything to the server.
2. (happened in my project) I had the similar architecture, so the situation was the same: when the bug occurred, only the timer future was active -- I received several messages from the server, but I've never got inside the `for_each(|message| { ... })` of my `Stream` future (which represents the stream of incoming messages). So the timer future was always "active" and other futures looked completely frozen (I even tried to add some `println!()` inside the `poll` function and it was not called). After the conditions had changed (as a consequence, the timer handler execution time became less than the interval time), only then I've noticed that other futures started to do something useful (and immediately received a bunch of messages which I received from the server within the last 20 seconds).

**Comment by carllerche** [comment] 2017-03-07 20:06
Are you saying that if a task is CPU bound then no other tasks on the executor run? If so, this is intended behavior. CPU bound tasks should run on a thread pool in order to not block execution.

**Comment by application-developer-DA** [comment] 2017-03-08 09:21
One of the functions which is called inside the timer's timeout handler is CPU bound, but the problem not in CPU bound function as such. The problem is what happens next. Take a look at the table in my coments above. `N+140ms` -- at this moment tokio had to switch to another task to perform some actions, but instead of that nothing happened, and so no futures were being processed at that point

**Comment by application-developer-DA** [comment] 2017-03-08 09:42
Ok, I wrote another one simple example. Both files are based on `chat.rs` and `connect.rs` from tokio-core examples. I changed some things. The server now pushes some messages to the connected clients. If you start the server (modified `chat.rs`) and then connect to it using the `connect.rs` example from tokio-core, it would work fine, you will see a messages from the server on the client side. However if you try to run the modified `connect.rs` (the one which contains the timer), you will see that the client does not receive any of the messages from the server, neither it sends one.

**Server:**

```rust
//! A chat server that broadcasts a message to all connections.
//!
//! This is a simple line-based server which accepts connections, reads lines
//! from those connections, and broadcasts the lines to all other connected
//! clients. In a sense this is a bit of a "poor man's chat server".
//!
//! You can test this out by running:
//!
//!     cargo run --example chat
//!
//! And then in another window run:
//!
//!     nc -4 localhost 8080
//!
//! You can run the second command in multiple windows and then chat between the
//! two, seeing the messages from the other client as they're received. For all
//! connected clients they'll all join the same room and see everyone else's
//! messages.

extern crate tokio_core;
extern crate futures;
extern crate tokio_timer;

use std::collections::HashMap;
use std::rc::Rc;
use std::cell::RefCell;
use std::iter;
use std::env;
use std::io::{Error, ErrorKind, BufReader};

use tokio_core::net::TcpListener;
use tokio_core::reactor::Core;
use tokio_core::io::{self, Io};

use futures::stream::{self, Stream};
use futures::Future;

fn main() {
    let addr = env::args().nth(1).unwrap_or("127.0.0.1:8080".to_string());
    let addr = addr.parse().unwrap();

    // Create the event loop and TCP listener we'll accept connections on.
    let mut core = Core::new().unwrap();
    let handle = core.handle();
    let socket = TcpListener::bind(&addr, &handle).unwrap();
    println!("Listening on: {}", addr);

    // This is a single-threaded server, so we can just use Rc and RefCell to
    // store the map of all connections we know about.
    let connections = Rc::new(RefCell::new(HashMap::new()));

    let srv = socket.incoming().for_each(move |(stream, addr)| {
        println!("New Connection: {}", addr);
        let (reader, writer) = stream.split();

        // Create a channel for our stream, which other sockets will use to
        // send us messages. Then register our address with the stream to send
        // data to us.
        let (tx, rx) = futures::sync::mpsc::unbounded();
        connections.borrow_mut().insert(addr, tx);

        // Define here what we do for the actual I/O. That is, read a bunch of
        // lines from the socket and dispatch them while we also write any lines
        // from other sockets.
        let connections_inner = connections.clone();
        let reader = BufReader::new(reader);

        // Model the read portion of this socket by mapping an infinite
        // iterator to each line off the socket. This "loop" is then
        // terminated with an error once we hit EOF on the socket.
        let iter = stream::iter(iter::repeat(()).map(Ok::<(), Error>));
        let socket_reader = iter.fold(reader, move |reader, _| {
            // Read a line off the socket, failing if we're at EOF
            let line = io::read_until(reader, b'\n', Vec::new());
            let line = line.and_then(|(reader, vec)| {
                if vec.len() == 0 {
                    Err(Error::new(ErrorKind::BrokenPipe, "broken pipe"))
                } else {
                    Ok((reader, vec))
                }
            });

            // Convert the bytes we read into a string, and then send that
            // string to all other connected clients.
            let line = line.map(|(reader, vec)| {
                (reader, String::from_utf8(vec))
            });
            let connections = connections_inner.clone();
            line.map(move |(reader, message)| {
                println!("{}: {:?}", addr, message);
                let mut conns = connections.borrow_mut();
                if let Ok(msg) = message {
                    // For each open connection except the sender, send the
                    // string via the channel.
                    let iter = conns.iter_mut()
                                    .filter(|&(&k, _)| k != addr)
                                    .map(|(_, v)| v);
                    for tx in iter {
                        tx.send(format!("{}: {}", addr, msg)).unwrap();
                    }
                } else {
                    let tx = conns.get_mut(&addr).unwrap();
                    tx.send("You didn't send valid UTF-8.".to_string()).unwrap();
                }
                reader
            })
        });

        // Whenever we receive a string on the Receiver, we write it to
        // `WriteHalf<TcpStream>`.
        let socket_writer = rx.fold(writer, |writer, msg| {
            let amt = io::write_all(writer, msg.into_bytes());
            let amt = amt.map(|(writer, _)| writer);
            amt.map_err(|_| ())
        });

        // Now that we've got futures representing each half of the socket, we
        // use the `select` combinator to wait for either half to be done to
        // tear down the other. Then we spawn off the result.
        let connections_in = connections.clone();
        let socket_reader = socket_reader.map_err(|_| ());
        let connection = socket_reader.map(|_| ()).select(socket_writer.map(|_| ()));
        handle.spawn(connection.then(move |_| {
            connections_in.borrow_mut().remove(&addr);
            println!("Connection {} closed.", addr);
            Ok(())
        }));

        let connections = connections.clone();
        let timer = tokio_timer::wheel().tick_duration(std::time::Duration::from_millis(10))
                                        .build()
                                        .interval(std::time::Duration::from_millis(200))
                                        .for_each(move |_| {
                                            println!("test");
                                            let mut conns = connections.borrow_mut();
                                            for item in conns.iter_mut() {
                                                item.1.send("Message from server\n".to_owned()).unwrap();
                                            }
                                            Ok(())
                                        });
        handle.spawn(timer.map_err(|_| ()));

        Ok(())
    });

    // execute server
    core.run(srv).unwrap();
}
```

**Client:**
```rust
//! A simple example of hooking up stdin/stdout to a TCP stream.
//!
//! This example will connect to a server specified in the argument list and
//! then forward all data read on stdin to the server, printing out all data
//! received on stdout.
//!
//! Note that this is not currently optimized for performance, especially around
//! buffer management. Rather it's intended to show an example of working with a
//! client.

extern crate futures;
extern crate tokio_core;
extern crate tokio_timer;

use std::env;
use std::io::{self, Read, Write};
use std::net::SocketAddr;
use std::thread;
use std::time::Duration;

use futures::{Sink, Future, Stream};
use futures::sync::mpsc;
use tokio_core::reactor::Core;
use tokio_core::io::{Io, EasyBuf, Codec};
use tokio_core::net::TcpStream;
use tokio_timer::Timer;

fn main() {
    // Parse what address we're going to connect to
    let addr = env::args().nth(1).unwrap_or_else(|| {
        panic!("this program requires at least one argument")
    });
    let addr = addr.parse::<SocketAddr>().unwrap();

    // Create the event loop and initiate the connection to the remote server
    let mut core = Core::new().unwrap();
    let handle = core.handle();
    let tcp = TcpStream::connect(&addr, &handle);

    // Right now Tokio doesn't support a handle to stdin running on the event
    // loop, so we farm out that work to a separate thread. This thread will
    // read data from stdin and then send it to the event loop over a standard
    // futures channel.
    let (stdin_tx, stdin_rx) = mpsc::channel(0);
    thread::spawn(|| read_stdin(stdin_tx));
    let stdin_rx = stdin_rx.map_err(|_| panic!()); // errors not possible on rx

    // After the TCP connection has been established, we set up our client to
    // start forwarding data.
    //
    // First we use the `Io::framed` method with a simple implementation of a
    // `Codec` (listed below) that just ships bytes around. We then split that
    // in two to work with the stream and sink separately.
    //
    // Half of the work we're going to do is to take all data we receive on
    // stdin (`stdin_rx`) and send that along the TCP stream (`sink`). The
    // second half is to take all the data we receive (`stream`) and then write
    // that to stdout. Currently we just write to stdout in a synchronous
    // fashion.
    //
    // Finally we set the client to terminate once either half of this work
    // finishes. If we don't have any more data to read or we won't receive any
    // more work from the remote then we can exit.
    let mut stdout = io::stdout();
    let client = tcp.and_then(|stream| {
        let (sink, stream) = stream.framed(Bytes).split();
        let send_stdin = stdin_rx.forward(sink);
        let write_stdout = stream.for_each(move |buf| {
            stdout.write_all(buf.as_slice())
        });

        const TICK_DURATION: u64 = 10;
        const TIMER_INTERVAL: u64 = 100;
        let timer = tokio_timer::wheel().tick_duration(Duration::from_millis(TICK_DURATION)).build();
        let timer = timer.interval(Duration::from_millis(TIMER_INTERVAL)).for_each(move |_| {
            // Let's simulate some CPU bound function which did not met the expected timeframe,
            // i.e. took longer than the `TIMER_INTERVAL`.
            std::thread::sleep(Duration::from_millis(TIMER_INTERVAL + 1));
            Ok(())
        });
        handle.spawn(timer.map_err(|_| ()));

        send_stdin.map(|_| ())
                  .select(write_stdout.map(|_| ()))
                  .then(|_| Ok(()))
    });

    // And now that we've got our client, we execute it in the event loop!
    core.run(client).unwrap();
}

/// A simple `Codec` implementation that just ships bytes around.
///
/// This type is used for "framing" a TCP stream of bytes but it's really just a
/// convenient method for us to work with streams/sinks for now. This'll just
/// take any data read and interpret it as a "frame" and conversely just shove
/// data into the output location without looking at it.
struct Bytes;

impl Codec for Bytes {
    type In = EasyBuf;
    type Out = Vec<u8>;

    fn decode(&mut self, buf: &mut EasyBuf) -> io::Result<Option<EasyBuf>> {
        if buf.len() > 0 {
            let len = buf.len();
            Ok(Some(buf.drain_to(len)))
        } else {
            Ok(None)
        }
    }

    fn encode(&mut self, data: Vec<u8>, buf: &mut Vec<u8>) -> io::Result<()> {
        buf.extend(data);
        Ok(())
    }
}

// Our helper method which will read data from stdin and send it along the
// sender provided.
fn read_stdin(mut rx: mpsc::Sender<Vec<u8>>) {
    let mut stdin = io::stdin();
    loop {
        let mut buf = vec![0; 1024];
        let n = match stdin.read(&mut buf) {
            Err(_) |
            Ok(0) => break,
            Ok(n) => n,
        };
        buf.truncate(n);
        rx = rx.send(buf).wait().unwrap();
    }
}
```

I think the expected behavior would be if we could still see messages coming from the server (after the timer timeout has been finished there is still a lot of time till the next timeout, tokio has to switch to another tasks to handle other futures), but it does not work this way.

**Comment by carllerche** [comment] 2017-03-08 21:09
Alright, I think I see what you mean. There is very probably a scheduling fairness issue that I will dig into. However, I would highly recommend to not run CPU intensive tasks on the tokio-core reactor. Instead, run them on futures-cpupool.

**Comment by carllerche** [comment] 2017-03-08 21:31
So, the issue is that your `for_each` over the interval stream is starving the reactor. Because the processing time is longer than the stream interval, the for_each runs in an infinite loop and control is never returned to the reactor.

**Comment by application-developer-DA** [comment] 2017-03-09 11:28
> Alright, I think I see what you mean. There is very probably a scheduling fairness issue that I will dig into. 

Thanks Carl, yeah, I think that was my of my major points.


> However, I would highly recommend to not run CPU intensive tasks on the tokio-core reactor. Instead, run them on futures-cpupool.

I thought about that, but the problem is that if I start the CPU intensive task in a futures-cpupool during timeout processing, I will still have to wait until it is completed, so the timer handling future will still take nearly the same amount of time. In additional it could be that I'll have to add an additional thread synchronization via mutexes.

> So, the issue is that your for_each over the interval stream is starving the reactor. Because the processing time is longer than the stream interval, the for_each runs in an infinite loop and control is never returned to the reactor.

But there is a plenty of time between the intervals, isn't it? I mean when the processing is finished, there is still some time left until the next timeout, right?

Or does it work this way: if we missed a timeout (due to the long processing of the previous one), the missed timeout will be fired right after the processing ot the previous one is finished?

**Comment by carllerche** [comment] 2017-03-09 14:48
> if we missed a timeout (due to the long processing of the previous one),
the missed timeout will be fired right after the processing ot the previous
one is finished?

That is correct

**Comment by application-developer-DA** [comment] 2017-03-09 17:49
Hm, understood.

So if I got it right, referring to [my table with timestamps](https://github.com/tokio-rs/tokio-timer/issues/9#issuecomment-284675446), the actual behavior at `N+140ms` would be "`tokio notices that we missed a timeout which should have occurred at N+100ms [due to the processing of the previous timeout which had occurred at N+0ms] and so it schedules handling of this timeout immediately and we're starting processing of this missed timeout`", is it correct?

If so, then it explains the observed behavior; you're right -- it seems to be related to the scheduling fairness.

**Comment by carllerche** [comment] 2017-03-09 20:49
Yep. There are a bunch of issues open in the futures-rs repository regarding yielding / fairness. So I'll close this issue in favor of those.

**Closed by carllerche** 2017-03-09 20:49 UTC
